# Generated by Django 2.2.4 on 2020-04-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('Roll_Number', models.IntegerField(primary_key=True, serialize=False)),
                ('Student_Name', models.CharField(max_length=30)),
                ('Mobile', models.BigIntegerField()),
                ('Fee', models.IntegerField()),
                ('Email', models.EmailField(max_length=50)),
                ('DateOfBirth', models.DateField(max_length=100)),
                ('Gender', models.CharField(max_length=20)),
                ('Course', models.CharField(max_length=20)),
                ('InstituteName', models.CharField(max_length=50)),
                ('Address', models.TimeField(max_length=50)),
            ],
        ),
    ]
