# Generated by Django 2.2.4 on 2020-04-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentRegistrationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='Address',
            field=models.TextField(max_length=50),
        ),
    ]
